@description('Location for all resources.')
param location string = resourceGroup().location

@description('A prefix to add to the start of all resource names. Note: A "unique" suffix will also be added')
param prefix string = 'demo'

@description('Tags to apply to all deployed resources')
param tags object = {}

@description('The URL to the deployment artifact to deploy, if left empty deployment will be skipped and you will need to deploy after the template is done')
param deploymentArtifactUrl string = ''

@description('The SKU to use for the App Service Plan')
param appServiceSku { name: string, tier: string } = {
  name: 'P2v4'
  tier: 'PremiumV4' 
}

@description('An authorization code that will need to be in the url to access the site. Set this to a blank string to disable auth code checking')
param authCode string = newGuid()

var uniqueNameFormat = '${prefix}-{0}-${uniqueString(resourceGroup().id, prefix)}'
var uniqueShortNameFormat = toLower('${prefix}{0}${uniqueString(resourceGroup().id, prefix)}')

resource logAnalytics 'Microsoft.OperationalInsights/workspaces@2023-09-01' = {
  name: format(uniqueNameFormat, 'logs')
  location: location
  tags: tags
  properties: {
    retentionInDays: 30
    sku: {
      name: 'PerGB2018'
    }
  }
}

resource appInsights 'Microsoft.Insights/components@2020-02-02-preview' = {
  name: format(uniqueNameFormat, 'appins')
  location: location
  kind: 'web'
  properties: {
    Application_Type: 'web'
    WorkspaceResourceId: logAnalytics.id
  }
}

resource aiSpeech 'Microsoft.CognitiveServices/accounts@2024-10-01' = {
  name: format(uniqueNameFormat, 'aispeech')
  location: location
  tags: tags
  kind: 'SpeechServices'
  sku: {
    name: 'S0'
  }
  properties: {
    customSubDomainName: format(uniqueShortNameFormat, 'aispeech')
    disableLocalAuth: true
  }
}

resource aiSpeechLogs 'Microsoft.Insights/diagnosticSettings@2021-05-01-preview' = {
  name: 'allLogsToLogAnalytics'
  scope: aiSpeech
  properties: {
    workspaceId: logAnalytics.id
    logs: [
      {
        categoryGroup: 'allLogs'
        enabled: true
      }
    ]
  }
}

resource appServicePlan 'Microsoft.Web/serverfarms@2024-04-01' = {
  name: format(uniqueNameFormat, 'asp')
  location: location
  tags: tags
  sku: {
    tier: appServiceSku.tier
    name: appServiceSku.name
    capacity: 1
  }
}

resource appService 'Microsoft.Web/sites@2024-04-01' = {
  name: format(uniqueNameFormat, 'backend')
  location: location
  tags: tags
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    serverFarmId: appServicePlan.id
    httpsOnly: true
    clientAffinityEnabled: true
    publicNetworkAccess: 'Enabled'
    autoGeneratedDomainNameLabelScope: 'NoReuse'
    siteConfig: {
      alwaysOn: true
      webSocketsEnabled: true
      ftpsState: 'Disabled'
      use32BitWorkerProcess: false
      appSettings: [
        {
          name: 'AzureAISpeech__Region'
          value: aiSpeech.location
        }
        {
          name: 'AzureAISpeech__ResourceID'
          value: aiSpeech.id
        }
        {
          name: 'AuthCode'
          value: authCode
        }
        {
          name: 'APPLICATIONINSIGHTS_CONNECTION_STRING'
          value: appInsights.properties.ConnectionString
        }
      ]
    }
  }
  resource disableScmBasicCredentials 'basicPublishingCredentialsPolicies@2024-04-01' = {
    name: 'scm'
    properties: { allow: false }
  }
  resource disableFtpBasicCredentials 'basicPublishingCredentialsPolicies@2024-04-01' = {
    name: 'ftp'
    properties: { allow: false }
  }
  resource zipDeploy 'extensions@2024-04-01' = if (!empty(trim(deploymentArtifactUrl))) {
    name: 'MSDeploy'
    properties: {
      packageUri: deploymentArtifactUrl
    }
  }
}

resource appServiceLogs 'Microsoft.Insights/diagnosticSettings@2021-05-01-preview' = {
  name: 'allLogsToLogAnalytics'
  scope: appService
  properties: {
    workspaceId: logAnalytics.id
    logs: [
      { category: 'AppServiceAntivirusScanAuditLogs', enabled: true }
      { category: 'AppServiceHTTPLogs', enabled: true }
      { category: 'AppServiceConsoleLogs', enabled: true }
      { category: 'AppServiceAppLogs', enabled: true }
      { category: 'AppServiceFileAuditLogs', enabled: true }
      { category: 'AppServiceAuditLogs', enabled: true }
      { category: 'AppServiceIPSecAuditLogs', enabled: true }
      { category: 'AppServicePlatformLogs', enabled: true }
      { category: 'AppServiceAuthenticationLogs', enabled: true }
    ]
  }
}

resource aiSpeechUserRole 'Microsoft.Authorization/roleDefinitions@2022-05-01-preview' existing = {
  scope: subscription()
  // Cognitive Services Speech User
  name: 'f2dc8367-1007-4938-bd23-fe263f013447'
}

resource aiSpeechRoleAssignment 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(aiSpeech.id, aiSpeechUserRole.id, appService.id)
  scope: aiSpeech
  properties: {
    roleDefinitionId: aiSpeechUserRole.id
    principalId: appService.identity.principalId
    principalType: 'ServicePrincipal'
  }
}
